In [3]:
import numpy as np

In [4]:
#corresponds to notes p11 (numpy)
L = [1,2,3]
L+=1

#list cannot 逐項加1

TypeError: 'int' object is not iterable

In [5]:
A = np.array(L)

A += 1
A

#arrray can 逐項加1

array([2, 3, 4])

In [6]:
for i in range(len(L)):
    L[i] += 1

In [7]:
L

[2, 3, 4]

In [8]:
#notes p20
b = np.array([[1,2],[3,4],[5,6]])
for ele in b:
    print (ele, end = ' ')

[1 2] [3 4] [5 6] 

In [9]:
for ele in b:
    for i in ele:
        print(i, end = ' ')

1 2 3 4 5 6 

In [10]:
#p 26 商店到公司的距離

store = np.array([2,1])
office = np.array([4,4])

store_office = office - store

norm_store_office = np.linalg.norm(store_office)
norm_store_office

3.605551275463989

In [12]:
a = np.array([1,2,3,4,5,6,7,8,9])

print (a)

#array[start:end:step]
b, c, d = a[1:3], a[1:4], a[3:]
print (b,c,d)

[1 2 3 4 5 6 7 8 9]
[2 3] [2 3 4] [4 5 6 7 8 9]


In [14]:
b,c,d = a[2:9:3], a[::2], a[::-1]
print (b,c,d)

[3 6 9] [1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [15]:
a = np.arange(11,36)
a = a.reshape(5,5)

In [16]:
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [22]:
b = a[:, 1]
print (b)

print (b.shape)

c = a[1,:]
print (c)
print (c.shape)

[12 17 22 27 32]
(5,)
[16 17 18 19 20]
(5,)
